-- ESG sensitivity weighting rules (top metrics by client preferences)

CREATE TABLE IF NOT EXISTS esg_metric_labels (
  metric_key VARCHAR(128) NOT NULL,
  label_fr VARCHAR(255) NOT NULL,
  unit VARCHAR(64) NULL,
  description TEXT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (metric_key)
);

CREATE TABLE IF NOT EXISTS esg_sensitivity_weights (
  id INT NOT NULL AUTO_INCREMENT,
  dimension VARCHAR(32) NOT NULL,
  dimension_key VARCHAR(128) NOT NULL,
  metric_key VARCHAR(128) NOT NULL,
  weight DECIMAL(10,4) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_esg_sensitivity (dimension, dimension_key, metric_key),
  KEY idx_esg_sensitivity_dim (dimension, dimension_key),
  KEY idx_esg_sensitivity_metric (metric_key)
);

-- Base labels (FR) for canonical keys used by default weights.
INSERT IGNORE INTO esg_metric_labels (metric_key, label_fr, unit, description) VALUES
  ('environmental_good', 'Contribution environnementale positive', NULL, NULL),
  ('environmental_harm', 'Impact environnemental negatif', NULL, NULL),
  ('pollution_positive', 'Pollution positive', NULL, NULL),
  ('pollution_negative', 'Pollution negative', NULL, NULL),
  ('pollution_net', 'Pollution nette', NULL, NULL),
  ('waste_efficiency', 'Efficacite des dechets', NULL, NULL),
  ('water_efficiency', 'Efficacite de l\'eau', NULL, NULL),
  ('biodiversity', 'Biodiversite', NULL, NULL),
  ('avoiding_water_scarcity', 'Evitement des tensions hydriques', NULL, NULL),
  ('ghg_intensity_value', 'Intensite GES', 'tCO2e/M€', NULL),
  ('scope_1_and_2_carbon_intensity', 'Emissions GES scope 1+2', 'tCO2e/M€', NULL),
  ('scope_3_carbon_intensity', 'Emissions GES scope 3', 'tCO2e/M€', NULL),
  ('carbon_trend', 'Tendance carbone', '%', NULL),
  ('temperature_score', 'Score de temperature', NULL, NULL),
  ('exposure_to_fossil_fuels', 'Exposition aux energies fossiles', '%', NULL),
  ('renewable_energy', 'Part d\'energie renouvelable', '%', NULL),
  ('violations_ungc', 'Violations des principes UNGC', '%', NULL),
  ('processes_ungc', 'Processus UNGC', '%', NULL),
  ('social_harm', 'Impact social negatif', NULL, NULL),
  ('social_good', 'Impact social positif', NULL, NULL),
  ('pct_female_board', 'Part de femmes au conseil', '%', NULL),
  ('pct_female_executives', 'Part de femmes dirigeantes', '%', NULL),
  ('board_gender_diversity', 'Mixite gouvernance', '%', NULL),
  ('gender_pay_gap', 'Ecart de remuneration H/F', '%', NULL),
  ('board_independence', 'Independance du conseil', '%', NULL),
  ('executive_pay', 'Renumaration des dirigeants', NULL, NULL),
  ('controversial_weapons', 'Exposition armes controversees', '%', NULL),
  ('note_e', 'Note E', NULL, NULL),
  ('note_s', 'Note S', NULL, NULL),
  ('note_g', 'Note G', NULL, NULL),
  ('note_esg', 'Note ESG', NULL, NULL);

-- Default weighted rules (dimension = question, keys = esg_questionnaire fields).
INSERT IGNORE INTO esg_sensitivity_weights (dimension, dimension_key, metric_key, weight) VALUES
  ('question', 'env_importance', 'environmental_good', 1.00),
  ('question', 'env_importance', 'environmental_harm', 1.00),
  ('question', 'env_importance', 'pollution_positive', 0.80),
  ('question', 'env_importance', 'pollution_negative', 0.80),
  ('question', 'env_importance', 'pollution_net', 0.60),
  ('question', 'env_importance', 'waste_efficiency', 0.70),
  ('question', 'env_importance', 'water_efficiency', 0.70),
  ('question', 'env_importance', 'biodiversity', 0.60),
  ('question', 'env_importance', 'avoiding_water_scarcity', 0.60),
  ('question', 'env_importance', 'note_e', 0.50),
  ('question', 'env_ges_reduc', 'ghg_intensity_value', 1.00),
  ('question', 'env_ges_reduc', 'scope_1_and_2_carbon_intensity', 0.90),
  ('question', 'env_ges_reduc', 'scope_3_carbon_intensity', 0.90),
  ('question', 'env_ges_reduc', 'carbon_trend', 0.80),
  ('question', 'env_ges_reduc', 'temperature_score', 0.80),
  ('question', 'env_ges_reduc', 'exposure_to_fossil_fuels', 0.70),
  ('question', 'env_ges_reduc', 'renewable_energy', 0.70),
  ('question', 'env_ges_reduc', 'note_e', 0.40),
  ('question', 'soc_droits_humains', 'violations_ungc', 1.00),
  ('question', 'soc_droits_humains', 'processes_ungc', 0.80),
  ('question', 'soc_droits_humains', 'social_harm', 0.70),
  ('question', 'soc_droits_humains', 'social_good', 0.60),
  ('question', 'soc_droits_humains', 'note_s', 0.40),
  ('question', 'soc_parite', 'pct_female_board', 0.90),
  ('question', 'soc_parite', 'pct_female_executives', 0.90),
  ('question', 'soc_parite', 'board_gender_diversity', 0.80),
  ('question', 'soc_parite', 'gender_pay_gap', 0.80),
  ('question', 'soc_parite', 'note_s', 0.40),
  ('question', 'gov_transparence', 'board_independence', 0.90),
  ('question', 'gov_transparence', 'executive_pay', 0.70),
  ('question', 'gov_transparence', 'processes_ungc', 0.60),
  ('question', 'gov_transparence', 'note_g', 0.40),
  ('question', 'gov_controle_ethique', 'controversial_weapons', 0.90),
  ('question', 'gov_controle_ethique', 'violations_ungc', 0.70),
  ('question', 'gov_controle_ethique', 'processes_ungc', 0.60),
  ('question', 'gov_controle_ethique', 'note_g', 0.40);
