-- Normalized ESG view (canonical snake_case), fed by esg_fonds with legacy fallback.
CREATE OR REPLACE VIEW esg_fonds_norm AS
SELECT
  ef.isin AS isin,
  COALESCE(ef.company_name, de.nom) AS name,
  COALESCE(ef.company_name, de.nom) AS company_name,
  ef.sector1 AS sector1,
  ef.mcap_usd AS mcap_usd,
  ef.revenue_usd AS revenue_usd,
  COALESCE(ef.processes_ungc, CAST(REPLACE(NULLIF(de.processesungc, ''), ',', '.') AS DECIMAL(20,6))) AS processes_ungc,
  COALESCE(ef.waste_efficiency, CAST(REPLACE(NULLIF(de.wasteefficiency, ''), ',', '.') AS DECIMAL(20,6))) AS waste_efficiency,
  COALESCE(ef.water_efficiency, CAST(REPLACE(NULLIF(de.waterefficiency, ''), ',', '.') AS DECIMAL(20,6))) AS water_efficiency,
  COALESCE(ef.environmental_good, CAST(REPLACE(NULLIF(de.environmentalgood, ''), ',', '.') AS DECIMAL(20,6))) AS environmental_good,
  COALESCE(ef.environmental_harm, CAST(REPLACE(NULLIF(de.environmentalharm, ''), ',', '.') AS DECIMAL(20,6))) AS environmental_harm,
  COALESCE(ef.ghg_intensity_value, CAST(REPLACE(NULLIF(de.ghgintensityvalue, ''), ',', '.') AS DECIMAL(20,6))) AS ghg_intensity_value,
  COALESCE(ef.emissions_to_water, CAST(REPLACE(NULLIF(de.emissionstowater, ''), ',', '.') AS DECIMAL(20,6))) AS emissions_to_water,
  COALESCE(ef.hazardous_waste, CAST(REPLACE(NULLIF(de.hazardouswaste, ''), ',', '.') AS DECIMAL(20,6))) AS hazardous_waste,
  COALESCE(ef.scope_1_and_2_carbon_intensity, CAST(REPLACE(NULLIF(de.scope1and2carbonintensity, ''), ',', '.') AS DECIMAL(20,6))) AS scope_1_and_2_carbon_intensity,
  COALESCE(ef.scope_3_carbon_intensity, CAST(REPLACE(NULLIF(de.scope3carbonintensity, ''), ',', '.') AS DECIMAL(20,6))) AS scope_3_carbon_intensity,
  COALESCE(CAST(REPLACE(NULLIF(de.carbontrend, ''), ',', '.') AS DECIMAL(20,6)), CAST(ef.carbon_trend AS DECIMAL(20,6))) AS carbon_trend,
  COALESCE(ef.temperature_score, CAST(REPLACE(NULLIF(de.temperaturescore, ''), ',', '.') AS DECIMAL(20,6))) AS temperature_score,
  COALESCE(ef.exposure_to_fossil_fuels, CAST(REPLACE(NULLIF(de.exposuretofossilfuels, ''), ',', '.') AS DECIMAL(20,6))) AS exposure_to_fossil_fuels,
  COALESCE(ef.renewable_energy, CAST(REPLACE(NULLIF(de.renewableenergy, ''), ',', '.') AS DECIMAL(20,6))) AS renewable_energy,
  ef.`climate_change__negative_revenue` AS climate_change__negative_revenue,
  ef.`pollution__positive_revenue` AS pollution__positive_revenue,
  ef.`pollution__negative_revenue` AS pollution__negative_revenue,
  COALESCE(ef.avoiding_water_scarcity, CAST(REPLACE(NULLIF(de.avoidingwaterscarcity, ''), ',', '.') AS DECIMAL(20,6))) AS avoiding_water_scarcity,
  COALESCE(ef.executive_pay, CAST(REPLACE(NULLIF(de.executivepay, ''), ',', '.') AS DECIMAL(20,6))) AS executive_pay,
  COALESCE(ef.social_good, CAST(REPLACE(NULLIF(de.socialgood, ''), ',', '.') AS DECIMAL(20,6))) AS social_good,
  COALESCE(ef.social_harm, CAST(REPLACE(NULLIF(de.socialharm, ''), ',', '.') AS DECIMAL(20,6))) AS social_harm,
  COALESCE(ef.average_per_employee_spend, CAST(REPLACE(NULLIF(de.avgperemployeespend, ''), ',', '.') AS DECIMAL(20,6))) AS average_per_employee_spend,
  COALESCE(ef.pct_female_board, CAST(REPLACE(NULLIF(de.pctfemaleboard, ''), ',', '.') AS DECIMAL(20,6))) AS pct_female_board,
  COALESCE(ef.pct_female_executives, CAST(REPLACE(NULLIF(de.pctfemaleexec, ''), ',', '.') AS DECIMAL(20,6))) AS pct_female_executives,
  COALESCE(ef.gender_pay_gap, CAST(REPLACE(NULLIF(de.genderpaygap, ''), ',', '.') AS DECIMAL(20,6))) AS gender_pay_gap,
  COALESCE(ef.board_gender_diversity, CAST(REPLACE(NULLIF(de.boardgenderdiversity, ''), ',', '.') AS DECIMAL(20,6))) AS board_gender_diversity,
  COALESCE(ef.board_independence, CAST(REPLACE(NULLIF(de.boardindependence, ''), ',', '.') AS DECIMAL(20,6))) AS board_independence,
  CAST(REPLACE(NULLIF(de.numberofemployees, ''), ',', '.') AS DECIMAL(20,6)) AS number_of_employees,
  CAST(REPLACE(NULLIF(de.biodiversity, ''), ',', '.') AS DECIMAL(20,6)) AS biodiversity,
  CAST(REPLACE(NULLIF(de.climateimpactrevenue, ''), ',', '.') AS DECIMAL(20,6)) AS climate_impact_revenue,
  CAST(REPLACE(NULLIF(de.climatechangepositive, ''), ',', '.') AS DECIMAL(20,6)) AS climate_change_positive,
  CAST(REPLACE(NULLIF(de.climatechangenegative, ''), ',', '.') AS DECIMAL(20,6)) AS climate_change_negative,
  CAST(REPLACE(NULLIF(de.climatechangenet, ''), ',', '.') AS DECIMAL(20,6)) AS climate_change_net,
  CAST(REPLACE(NULLIF(de.naturalresourcepositive, ''), ',', '.') AS DECIMAL(20,6)) AS natural_resource_positive,
  CAST(REPLACE(NULLIF(de.naturalresourcenegative, ''), ',', '.') AS DECIMAL(20,6)) AS natural_resource_negative,
  CAST(REPLACE(NULLIF(de.naturalresourcenet, ''), ',', '.') AS DECIMAL(20,6)) AS natural_resource_net,
  COALESCE(ef.`pollution__positive_revenue`, CAST(REPLACE(NULLIF(de.pollutionpositive, ''), ',', '.') AS DECIMAL(20,6))) AS pollution_positive,
  COALESCE(ef.`pollution__negative_revenue`, CAST(REPLACE(NULLIF(de.pollutionnegative, ''), ',', '.') AS DECIMAL(20,6))) AS pollution_negative,
  CAST(REPLACE(NULLIF(de.pollutionnet, ''), ',', '.') AS DECIMAL(20,6)) AS pollution_net,
  CAST(REPLACE(NULLIF(de.sfdrbiodiversitypai, ''), ',', '.') AS DECIMAL(20,6)) AS sfdr_biodiversity_pai,
  CAST(REPLACE(NULLIF(de.controversialweapons, ''), ',', '.') AS DECIMAL(20,6)) AS controversial_weapons,
  CAST(REPLACE(NULLIF(de.violationsungc, ''), ',', '.') AS DECIMAL(20,6)) AS violations_ungc,
  COALESCE(ef.note_e, CAST(REPLACE(NULLIF(de.notee, ''), ',', '.') AS DECIMAL(20,6))) AS note_e,
  COALESCE(ef.note_s, CAST(REPLACE(NULLIF(de.notes, ''), ',', '.') AS DECIMAL(20,6))) AS note_s,
  COALESCE(ef.note_g, CAST(REPLACE(NULLIF(de.noteg, ''), ',', '.') AS DECIMAL(20,6))) AS note_g,
  ef.note_esg AS note_esg,
  ef.evic AS evic
FROM esg_fonds ef
LEFT JOIN donnees_esg_etendu de ON de.isin = ef.isin

UNION ALL

SELECT
  de.isin AS isin,
  de.nom AS name,
  de.nom AS company_name,
  NULL AS sector1,
  NULL AS mcap_usd,
  NULL AS revenue_usd,
  CAST(REPLACE(NULLIF(de.processesungc, ''), ',', '.') AS DECIMAL(20,6)) AS processes_ungc,
  CAST(REPLACE(NULLIF(de.wasteefficiency, ''), ',', '.') AS DECIMAL(20,6)) AS waste_efficiency,
  CAST(REPLACE(NULLIF(de.waterefficiency, ''), ',', '.') AS DECIMAL(20,6)) AS water_efficiency,
  CAST(REPLACE(NULLIF(de.environmentalgood, ''), ',', '.') AS DECIMAL(20,6)) AS environmental_good,
  CAST(REPLACE(NULLIF(de.environmentalharm, ''), ',', '.') AS DECIMAL(20,6)) AS environmental_harm,
  CAST(REPLACE(NULLIF(de.ghgintensityvalue, ''), ',', '.') AS DECIMAL(20,6)) AS ghg_intensity_value,
  CAST(REPLACE(NULLIF(de.emissionstowater, ''), ',', '.') AS DECIMAL(20,6)) AS emissions_to_water,
  CAST(REPLACE(NULLIF(de.hazardouswaste, ''), ',', '.') AS DECIMAL(20,6)) AS hazardous_waste,
  CAST(REPLACE(NULLIF(de.scope1and2carbonintensity, ''), ',', '.') AS DECIMAL(20,6)) AS scope_1_and_2_carbon_intensity,
  CAST(REPLACE(NULLIF(de.scope3carbonintensity, ''), ',', '.') AS DECIMAL(20,6)) AS scope_3_carbon_intensity,
  CAST(REPLACE(NULLIF(de.carbontrend, ''), ',', '.') AS DECIMAL(20,6)) AS carbon_trend,
  CAST(REPLACE(NULLIF(de.temperaturescore, ''), ',', '.') AS DECIMAL(20,6)) AS temperature_score,
  CAST(REPLACE(NULLIF(de.exposuretofossilfuels, ''), ',', '.') AS DECIMAL(20,6)) AS exposure_to_fossil_fuels,
  CAST(REPLACE(NULLIF(de.renewableenergy, ''), ',', '.') AS DECIMAL(20,6)) AS renewable_energy,
  NULL AS climate_change__negative_revenue,
  NULL AS pollution__positive_revenue,
  NULL AS pollution__negative_revenue,
  CAST(REPLACE(NULLIF(de.avoidingwaterscarcity, ''), ',', '.') AS DECIMAL(20,6)) AS avoiding_water_scarcity,
  CAST(REPLACE(NULLIF(de.executivepay, ''), ',', '.') AS DECIMAL(20,6)) AS executive_pay,
  CAST(REPLACE(NULLIF(de.socialgood, ''), ',', '.') AS DECIMAL(20,6)) AS social_good,
  CAST(REPLACE(NULLIF(de.socialharm, ''), ',', '.') AS DECIMAL(20,6)) AS social_harm,
  CAST(REPLACE(NULLIF(de.avgperemployeespend, ''), ',', '.') AS DECIMAL(20,6)) AS average_per_employee_spend,
  CAST(REPLACE(NULLIF(de.pctfemaleboard, ''), ',', '.') AS DECIMAL(20,6)) AS pct_female_board,
  CAST(REPLACE(NULLIF(de.pctfemaleexec, ''), ',', '.') AS DECIMAL(20,6)) AS pct_female_executives,
  CAST(REPLACE(NULLIF(de.genderpaygap, ''), ',', '.') AS DECIMAL(20,6)) AS gender_pay_gap,
  CAST(REPLACE(NULLIF(de.boardgenderdiversity, ''), ',', '.') AS DECIMAL(20,6)) AS board_gender_diversity,
  CAST(REPLACE(NULLIF(de.boardindependence, ''), ',', '.') AS DECIMAL(20,6)) AS board_independence,
  CAST(REPLACE(NULLIF(de.numberofemployees, ''), ',', '.') AS DECIMAL(20,6)) AS number_of_employees,
  CAST(REPLACE(NULLIF(de.biodiversity, ''), ',', '.') AS DECIMAL(20,6)) AS biodiversity,
  CAST(REPLACE(NULLIF(de.climateimpactrevenue, ''), ',', '.') AS DECIMAL(20,6)) AS climate_impact_revenue,
  CAST(REPLACE(NULLIF(de.climatechangepositive, ''), ',', '.') AS DECIMAL(20,6)) AS climate_change_positive,
  CAST(REPLACE(NULLIF(de.climatechangenegative, ''), ',', '.') AS DECIMAL(20,6)) AS climate_change_negative,
  CAST(REPLACE(NULLIF(de.climatechangenet, ''), ',', '.') AS DECIMAL(20,6)) AS climate_change_net,
  CAST(REPLACE(NULLIF(de.naturalresourcepositive, ''), ',', '.') AS DECIMAL(20,6)) AS natural_resource_positive,
  CAST(REPLACE(NULLIF(de.naturalresourcenegative, ''), ',', '.') AS DECIMAL(20,6)) AS natural_resource_negative,
  CAST(REPLACE(NULLIF(de.naturalresourcenet, ''), ',', '.') AS DECIMAL(20,6)) AS natural_resource_net,
  CAST(REPLACE(NULLIF(de.pollutionpositive, ''), ',', '.') AS DECIMAL(20,6)) AS pollution_positive,
  CAST(REPLACE(NULLIF(de.pollutionnegative, ''), ',', '.') AS DECIMAL(20,6)) AS pollution_negative,
  CAST(REPLACE(NULLIF(de.pollutionnet, ''), ',', '.') AS DECIMAL(20,6)) AS pollution_net,
  CAST(REPLACE(NULLIF(de.sfdrbiodiversitypai, ''), ',', '.') AS DECIMAL(20,6)) AS sfdr_biodiversity_pai,
  CAST(REPLACE(NULLIF(de.controversialweapons, ''), ',', '.') AS DECIMAL(20,6)) AS controversial_weapons,
  CAST(REPLACE(NULLIF(de.violationsungc, ''), ',', '.') AS DECIMAL(20,6)) AS violations_ungc,
  CAST(REPLACE(NULLIF(de.notee, ''), ',', '.') AS DECIMAL(20,6)) AS note_e,
  CAST(REPLACE(NULLIF(de.notes, ''), ',', '.') AS DECIMAL(20,6)) AS note_s,
  CAST(REPLACE(NULLIF(de.noteg, ''), ',', '.') AS DECIMAL(20,6)) AS note_g,
  NULL AS note_esg,
  NULL AS evic
FROM donnees_esg_etendu de
LEFT JOIN esg_fonds ef ON ef.isin = de.isin
WHERE ef.isin IS NULL;

-- Legacy compatibility view (old camel/compact naming).
CREATE OR REPLACE VIEW donnees_esg_etendu_compat AS
SELECT
  isin,
  name AS nom,
  waste_efficiency AS wasteefficiency,
  water_efficiency AS waterefficiency,
  executive_pay AS executivepay,
  board_independence AS boardindependence,
  environmental_good AS environmentalgood,
  social_good AS socialgood,
  environmental_harm AS environmentalharm,
  social_harm AS socialharm,
  number_of_employees AS numberofemployees,
  average_per_employee_spend AS avgperemployeespend,
  pct_female_board AS pctfemaleboard,
  pct_female_executives AS pctfemaleexec,
  ghg_intensity_value AS ghgintensityvalue,
  biodiversity AS biodiversity,
  emissions_to_water AS emissionstowater,
  hazardous_waste AS hazardouswaste,
  violations_ungc AS violationsungc,
  processes_ungc AS processesungc,
  gender_pay_gap AS genderpaygap,
  board_gender_diversity AS boardgenderdiversity,
  controversial_weapons AS controversialweapons,
  scope_1_and_2_carbon_intensity AS scope1and2carbonintensity,
  scope_3_carbon_intensity AS scope3carbonintensity,
  carbon_trend AS carbontrend,
  temperature_score AS temperaturescore,
  exposure_to_fossil_fuels AS exposuretofossilfuels,
  renewable_energy AS renewableenergy,
  climate_impact_revenue AS climateimpactrevenue,
  climate_change_positive AS climatechangepositive,
  climate_change_negative AS climatechangenegative,
  climate_change_net AS climatechangenet,
  natural_resource_positive AS naturalresourcepositive,
  natural_resource_negative AS naturalresourcenegative,
  natural_resource_net AS naturalresourcenet,
  pollution_positive AS pollutionpositive,
  pollution_negative AS pollutionnegative,
  pollution_net AS pollutionnet,
  avoiding_water_scarcity AS avoidingwaterscarcity,
  sfdr_biodiversity_pai AS sfdrbiodiversitypai,
  note_e AS notee,
  note_s AS notes,
  note_g AS noteg
FROM esg_fonds_norm;
