-- ESG metric averages and coverage (filtered to rows with E/S/G/ESG notes)
CREATE OR REPLACE VIEW esg_metric_averages AS
SELECT
  COUNT(*) AS sample_total,
  AVG(environmental_good) AS environmental_good_avg,
  ROUND(100 * SUM(environmental_good IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS environmental_good_coverage_pct,
  AVG(environmental_harm) AS environmental_harm_avg,
  ROUND(100 * SUM(environmental_harm IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS environmental_harm_coverage_pct,
  AVG(pollution_positive) AS pollution_positive_avg,
  ROUND(100 * SUM(pollution_positive IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS pollution_positive_coverage_pct,
  AVG(pollution_negative) AS pollution_negative_avg,
  ROUND(100 * SUM(pollution_negative IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS pollution_negative_coverage_pct,
  AVG(pollution_net) AS pollution_net_avg,
  ROUND(100 * SUM(pollution_net IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS pollution_net_coverage_pct,
  AVG(waste_efficiency) AS waste_efficiency_avg,
  ROUND(100 * SUM(waste_efficiency IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS waste_efficiency_coverage_pct,
  AVG(water_efficiency) AS water_efficiency_avg,
  ROUND(100 * SUM(water_efficiency IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS water_efficiency_coverage_pct,
  AVG(biodiversity) AS biodiversity_avg,
  ROUND(100 * SUM(biodiversity IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS biodiversity_coverage_pct,
  AVG(avoiding_water_scarcity) AS avoiding_water_scarcity_avg,
  ROUND(100 * SUM(avoiding_water_scarcity IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS avoiding_water_scarcity_coverage_pct,
  AVG(ghg_intensity_value) AS ghg_intensity_value_avg,
  ROUND(100 * SUM(ghg_intensity_value IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS ghg_intensity_value_coverage_pct,
  AVG(scope_1_and_2_carbon_intensity) AS scope_1_and_2_carbon_intensity_avg,
  ROUND(100 * SUM(scope_1_and_2_carbon_intensity IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS scope_1_and_2_carbon_intensity_coverage_pct,
  AVG(scope_3_carbon_intensity) AS scope_3_carbon_intensity_avg,
  ROUND(100 * SUM(scope_3_carbon_intensity IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS scope_3_carbon_intensity_coverage_pct,
  AVG(carbon_trend) AS carbon_trend_avg,
  ROUND(100 * SUM(carbon_trend IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS carbon_trend_coverage_pct,
  AVG(temperature_score) AS temperature_score_avg,
  ROUND(100 * SUM(temperature_score IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS temperature_score_coverage_pct,
  AVG(exposure_to_fossil_fuels) AS exposure_to_fossil_fuels_avg,
  ROUND(100 * SUM(exposure_to_fossil_fuels IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS exposure_to_fossil_fuels_coverage_pct,
  AVG(renewable_energy) AS renewable_energy_avg,
  ROUND(100 * SUM(renewable_energy IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS renewable_energy_coverage_pct,
  AVG(violations_ungc) AS violations_ungc_avg,
  ROUND(100 * SUM(violations_ungc IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS violations_ungc_coverage_pct,
  AVG(processes_ungc) AS processes_ungc_avg,
  ROUND(100 * SUM(processes_ungc IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS processes_ungc_coverage_pct,
  AVG(social_harm) AS social_harm_avg,
  ROUND(100 * SUM(social_harm IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS social_harm_coverage_pct,
  AVG(social_good) AS social_good_avg,
  ROUND(100 * SUM(social_good IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS social_good_coverage_pct,
  AVG(pct_female_board) AS pct_female_board_avg,
  ROUND(100 * SUM(pct_female_board IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS pct_female_board_coverage_pct,
  AVG(pct_female_executives) AS pct_female_executives_avg,
  ROUND(100 * SUM(pct_female_executives IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS pct_female_executives_coverage_pct,
  AVG(board_gender_diversity) AS board_gender_diversity_avg,
  ROUND(100 * SUM(board_gender_diversity IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS board_gender_diversity_coverage_pct,
  AVG(gender_pay_gap) AS gender_pay_gap_avg,
  ROUND(100 * SUM(gender_pay_gap IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS gender_pay_gap_coverage_pct,
  AVG(board_independence) AS board_independence_avg,
  ROUND(100 * SUM(board_independence IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS board_independence_coverage_pct,
  AVG(executive_pay) AS executive_pay_avg,
  ROUND(100 * SUM(executive_pay IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS executive_pay_coverage_pct,
  AVG(controversial_weapons) AS controversial_weapons_avg,
  ROUND(100 * SUM(controversial_weapons IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS controversial_weapons_coverage_pct,
  AVG(note_e) AS note_e_avg,
  ROUND(100 * SUM(note_e IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS note_e_coverage_pct,
  AVG(note_s) AS note_s_avg,
  ROUND(100 * SUM(note_s IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS note_s_coverage_pct,
  AVG(note_g) AS note_g_avg,
  ROUND(100 * SUM(note_g IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS note_g_coverage_pct,
  AVG(note_esg) AS note_esg_avg,
  ROUND(100 * SUM(note_esg IS NOT NULL) / NULLIF(COUNT(*), 0), 2) AS note_esg_coverage_pct
FROM esg_fonds_norm
WHERE note_e IS NOT NULL
  AND note_s IS NOT NULL
  AND note_g IS NOT NULL
  AND note_esg IS NOT NULL;
